disabled_rules:
- trailing_whitespace
- vertical_parameter_alignment
- switch_case_alignment
- multiple_closures_with_trailing_closure

opt_in_rules:
- empty_count
- empty_string
- sorted_imports

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 50
    error: 61

function_parameter_count:
    warning: 7
    error: 10

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25

identifier_name:
    min_length:
        warning: 2
    max_length: 40

force_cast:
    warning

reporter: "xcode"
